name: Logstash

# Only on Development we build snapshots
on:
  push:
    branches:
      - development
      - main

env:
  MODULE_ID: logstash

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      ELASTICSEARCH_PROTOCOL: http
      ELASTICSEARCH_HOST: 127.0.0.1
      ELASTICSEARCH_PORT: 9200
      LOGSTASH_API_URL: http://localhost:60299/logstash/api/logs
    strategy:
      fail-fast: true
      matrix:
        cfengine: ["lucee@5", "adobe@2018", "adobe@2021" ]
        ELASTICSEARCH_VERSION: [ "7.17.2", "8.6.0" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Setup Elasticsearch
        run: |
          docker run -d -p "${{ env.ELASTICSEARCH_PORT }}:9200" -e 'discovery.type=single-node' -e 'xpack.security.enabled=false' elasticsearch:${{ matrix.ELASTICSEARCH_VERSION }}

      - name: Install Dependencies
        run: |
          box install commandbox-cfconfig,commandbox-dotenv,commandbox-docbox
          box run-script harness:install

      - name: Start ${{ matrix.cfengine }} Server
        run: |
          cd ${GITHUB_WORKSPACE}/test-harness
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --debug
          sleep 60
          curl http://127.0.0.1:60299

      - name: Run Web App Tests
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir -p ${GITHUB_WORKSPACE}/test-harness/tests/results/web
          box package set testbox.runner="http://127.0.0.1:60299/tests/runner.cfm?seed=true"
          box testbox run --verbose outputFile=test-harness/tests/results/web/test-results outputFormats=json,antjunit

      - name: Publish Test Reports
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'test-harness/tests/results/*.xml'
          check_name: "${{ matrix.cfengine }}/${{ matrix.javaVersion }} Test Results"
          summary: true

      - name: Failure debugging
        if: ${{ failure() }}
        run: cd ${GITHUB_WORKSPACE}/test-harness && box server log serverConfigFile="server-${{ matrix.cfengine }}.json"
  #############################################
  # Build Logstash
  #############################################
  build:
    name: Build & Publish
    runs-on: ubuntu-20.04
    needs: tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@main
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_TOKEN }}

      - name: Setup Environment Variables For Build Process
        id: current_version
        run: |
          echo "VERSION=`cat box.json | jq '.version' -r`" >> $GITHUB_ENV
          box package set version=@build.version@+@build.number@
          # main or snapshot
          echo "Github Ref is $GITHUB_REF"
          echo "BRANCH=main" >> $GITHUB_ENV
          if [ $GITHUB_REF == 'refs/heads/development' ]
          then
            echo "BRANCH=development" >> $GITHUB_ENV
          fi
      - name: Build ${{ env.MODULE_ID }}
        run: |
          box install commandbox-docbox
          box task run taskfile=build/Build target=run :version=${{ env.VERSION }} :projectName=${{ env.MODULE_ID }} :buildID=${{ github.run_number }} :branch=${{ env.BRANCH }}
      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.MODULE_ID }}
          path: |
            .artifacts/**/*
      - name: Upload Binaries to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "downloads.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".artifacts/${{ env.MODULE_ID }}"
          DEST_DIR: "ortussolutions/coldbox-modules/${{ env.MODULE_ID }}"

      - name: Publish To ForgeBox
        run: |
          cd ${GITHUB_WORKSPACE}/.tmp/${{ env.MODULE_ID }}
          cat box.json
          box forgebox publish
      - name: Inform Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coding
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: '${{ env.MODULE_ID }} Built with ${{ job.status }}!'
          SLACK_TITLE: "${{ env.MODULE_ID }} Build"
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
